version: "3.8"

services:
  web:
    image: mansalien/vision_app:v0.7
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ~/orders:/root/orders
    env_file:
      - .env
    depends_on:
      - postgres_db
    restart: always

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${P_DATABASE}
      - POSTGRES_USER=${P_USER}
      - POSTGRES_PASSWORD=${P_PASSWORD}
    restart: always

  backup:
    image: postgres
    volumes:
      - ./db_backup:/backup
    command: >
      bash -c "while true; do
        PGPASSWORD=AAsd@01203394542 pg_dump -h postgres_db -U alien -Fc vision > /backup/$$(date +%Y-%m-%d-%H-%M-%S).dump
        echo ""Backup done at $$(date +%Y-%m-%d_%H:%M:%S)""
        ls -1 /backup/*.dump | head -n -5 | xargs rm -f
        sleep 43200
      done"
    environment:
      - P_DATABASE=${P_DATABASE}
      - P_USER=${P_USER}
      - P_PASSWORD=${P_PASSWORD}
    depends_on:
      - postgres_db

volumes:
  postgres_data:
