version: "3.8"

services:
  web:
    image: mansalien/vision_app:v0.5
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ~/orders:/root/orders
    env_file:
      - .env
    depends_on:
      - postgres_db
    restart: always

  postgres_db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${P_DATABASE}
      - POSTGRES_USER=${P_USER}
      - POSTGRES_PASSWORD=${P_PASSWORD}
    restart: always

  backup:
    build: ./backup
    volumes:
      - backup_data:/backups
    environment:
      - P_DATABASE=${P_DATABASE}
      - P_USER=${P_USER}
      - P_PASSWORD=${P_PASSWORD}
    depends_on:
      - postgres_db

volumes:
  postgres_data:
  backup_data:
