# Generated by Django 5.0.2 on 2024-04-17 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitlehistory',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
