# Generated by Django 5.0.2 on 2024-04-17 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_jobtitlehistory_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryhistory',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
