# Generated by Django 5.0.2 on 2024-04-06 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitlehistory',
            name='end',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='jobtitlehistory',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.jobtitle'),
        ),
        migrations.AlterField(
            model_name='jobtitlehistory',
            name='start',
            field=models.DateField(auto_now=True),
        ),
    ]
