# Generated by Django 5.0.2 on 2024-04-06 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_jobtitlehistory_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitlehistory',
            name='start',
            field=models.DateField(),
        ),
    ]
