# Generated by Django 5.0.2 on 2024-04-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_salaryhistory_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaryhistory',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
