# Generated by Django 5.0.2 on 2024-04-06 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_jobtitlehistory_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitlehistory',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile'),
        ),
    ]
