# Generated by Django 5.0.2 on 2024-04-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_salaryhistory_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
