# Generated by Django 5.0.2 on 2024-04-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_jobtitlehistory_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmenthistory',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='departmenthistory',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
