# Generated by Django 5.0.2 on 2024-04-06 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_departmenthistory_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobtitlehistory',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='jobtitlehistory',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
