# Generated by Django 5.0.2 on 2024-05-02 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_delete_loggedinuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deduction",
            name="date",
            field=models.DateTimeField(null=True),
        ),
    ]
