# Generated by Django 5.0.2 on 2024-04-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='deduction',
            name='discription',
            field=models.TextField(default=''),
        ),
    ]
