# Generated by Django 5.0.2 on 2024-05-20 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productline",
            name="admin_comment",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="orderdetail",
            name="location",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
