# Generated by Django 5.0.2 on 2024-05-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productline",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
