# Generated by Django 5.0.2 on 2024-06-06 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
