# Generated by Django 5.0.2 on 2024-05-20 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_productline_admin_comment_alter_orderdetail_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attribute",
            old_name="description",
            new_name="discription",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="description",
            new_name="discription",
        ),
    ]
