# Generated by Django 5.0.2 on 2024-05-12 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_productline_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sub_category",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="orders.category"
            ),
        ),
    ]
