# Generated by Django 5.0.2 on 2024-05-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_rename_description_attribute_discription_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attribute",
            old_name="discription",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="discription",
            new_name="description",
        ),
    ]
