# Generated by Django 5.0.2 on 2024-05-12 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_sub_category_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attribute",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="orders.sub_category"
            ),
        ),
        migrations.AlterField(
            model_name="sub_category",
            name="name",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
