# Generated by Django 5.0.2 on 2024-05-29 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_alter_customer_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="whatsapp",
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
