# Generated by Django 5.0.2 on 2024-05-18 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0006_remove_comment_customer_comment_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productline",
            name="deliver_date",
            field=models.IntegerField(null=True),
        ),
    ]
