# Generated by Django 5.0.2 on 2024-06-16 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_payment_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='path',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
