# Generated by Django 5.0.2 on 2024-07-20 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
