# Generated by Django 5.0.2 on 2024-07-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_alter_uploadimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='image',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
    ]
