# Generated by Django 5.0.2 on 2024-07-31 18:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_uploadimage_image_uploadimage_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UploadImage',
            new_name='UploadFile',
        ),
    ]
